version: "3.7"

services:
  reverse-proxy:
    image: traefik:v2.10
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker=true"
      - "--entrypoints.myweb.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal_network
  tinyurl:
    image: example/tinyurl
    build:
      context: .
      dockerfile: Dockerfile
    hostname: tinyurl
    restart: always
    ports:
      - 9000
    depends_on:
      - mongodb
      - redis
      - zookeeper
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodbserver
      - SPRING_REDIS_HOST=redisserver
      - SPRING_ZOOKEEPER_HOST=zookeeperserver:2181
    # below are only needed to connect with traefik load balancer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tinyurl.rule=Host(`server.localhost`)"
      - "traefik.http.routers.tinyurl.entrypoints=myweb"
    networks:
      - internal_network
  #    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
  mongodb:
    hostname: mongodbserver
    container_name: mongodb
    image: mongo
    depends_on:
      - zookeeper
    expose:
      - 27017
    restart: always
    volumes:
      - ./dockerdata/mongodb:/data/db
      - ./dockerdata/mongodb/configdb:/data/configdb
    networks:
      - internal_network
  #    entrypoint: [ "/usr/bin/mongod"]
  redis:
    hostname: redisserver
    container_name: redisserver
    image: redis
    depends_on:
      - zookeeper
    expose:
      - 6379
    networks:
      - internal_network
  zookeeper:
    image: zookeeper
    hostname: zookeeperserver
    container_name: zookeeperserver
    ports:
      - 2181
      - 2888
      - 3888
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_PEER_PORT: 2888
      ZOOKEEPER_LEADER_PORT: 3888
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
    volumes:
      - ./dockerdata/zookeeper:/data
      - ./dockerdata/zookeeper/logs:/logs
      - ./dockerdata/zookeeper/datalog:/datalog
      - ./configs/zookeeper_setup.sh:/start.sh
      - ./configs/zoo.cfg:/conf/zoo.cfg
    networks:
      - internal_network
    entrypoint: ["bash", "/start.sh"]
networks:
  internal_network:
    name: internal_network
    driver: bridge