spring:
#  application:
#    name: testZookeeperApp
  cache:
    redis:
      cache-null-values: on
      time-to-live: 40000
    type: redis
  data:
    mongodb:
      database: ${SPRING_MONGODB_DBNAME:urls}
      port: ${SPRING_MONGODB_PORT:27017}
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      auto-index-creation: true
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
  cloud:
    zookeeper:
      connect: ${SPRING_ZOOKEEPER_HOST:localhost:2181}
#      discovery:
#        enabled: true
#      config:
#        enabled: false
#        root: configuration
#        defaultContext: apps
#        profileSeparator: '::'
server:
  port: ${SPRING_SERVER_PORT:11000}
  endpoints:
    restart:
      enabled: true
    shutdown:
      enabled: true
    health:
      sensitive: false
  shutdown: graceful
logging.level:
  org.apache.zookeeper.ClientCnxn: ERROR
management:
  security:
    enabled: false
